Talentia/Controllers/ConfirmMailController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Talentia.Models;

namespace eticaret_uygula.Controllers
{
    public class ConfirmMailController : Controller
    {
        private readonly UserManager<AppUser> _userManager;

        public ConfirmMailController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var value = TempData["Mail"];
            ViewBag.Email = value;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index(ConfirmUser gelen)
        {
            var user = await _userManager.FindByEmailAsync(gelen.Mail);
            if (user.ConfirmCode == gelen.ConfirmCode)
            {
                user.EmailConfirmed = true;
                await _userManager.UpdateAsync(user);
                return RedirectToAction("Index", "Login");

            }
            return View();
        }
    }
}

Talentia/Views/ConfirmMail/Index.cshtml
@model Talentia.Models.ConfirmUser
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<h1>Mail Onaylama Formu</h1>

<form method="post" asp-action="Index" asp-controller="ConfirmMail">
    <div class="from-group">
        <h2>Onay Formundaki Gönderilen Mail Adresiniz:@ViewBag.Email</h2>
        <input class="form-control" type="text" value="@ViewBag.Email" asp-for="Mail"/>
    </div>
    <div class="form-group">
        <h2>Onay Kodunuzu Girin:</h2>
        <input type="text" class="form-control" asp-for="ConfirmCode"/>
    </div>
    <div class="form-group">
        <button class="btn btn-primary" type="submit">Hesabı Onayla</button>
    </div>
</form>